config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :owners
  devise_for :users
  resources :owners
  resources :sites do
    get :welcome
    resources :users do
      member do
        get :following, :followers
        post :contact
      end
    end
    resources :posts,    only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :user_sessions,      only: [:new, :create, :destroy]
    match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'user_sessions#new',         via: 'get'
    match '/signout', to: 'user_sessions#destroy',     via: 'delete'
  end
  resources :sessions,      only: [:new, :create, :destroy]
  match '/signup',  to: 'owners#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  root to: 'static_pages#home'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
    <span class="user">
      <%= link_to feed_item.user.name, site_user_path(id: feed_item.user.id) %>
    </span>
    <p><span class="content">Wants: <%= feed_item.wants_item %><% unless feed_item.wants_description.blank? %> - <% end %><%= feed_item.wants_description %></span></p>
    <p><span class="content">Has: <%= feed_item.has_item %><% unless feed_item.has_description.blank? %> - <% end %><%= feed_item.has_description %></span></p>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", site_post_path(id: feed_item.id), method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/shared/_post_form.html.erb
<%= form_for([:site, @post]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :site_id, value: params[:site_id] %>
  <h2 class="post">Enter an item that you want</h2>
  <div class="field styled-select">
    <%= f.select :wants_item, @site.trade_list %>
  </div>
  <h2 class="post">Description</h2>
  <div class="field styled-desc">
    <%= f.text_field :wants_description %>
  </div>
  <br>
  <h2 class="post">Enter an item that you have</h2>
  <div class="field styled-select">
    <%= f.select :has_item, @site.trade_list%>
  </div>
  <h2 class="post">Description</h2>
  <div class="field styled-desc">
    <%= f.text_field :has_description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  </div>
  <br>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(id: @user.id) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(id: @user.id) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= site_user_path(id: current_user.id) %>">
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", site_user_path(id: current_user.id) %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>