config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :owners
  devise_for :users
  resources :owners
  resources :sites do
    get :welcome
    resources :users do
      member do
        get :following, :followers
        post :contact
      end
    end
    resources :posts,    only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :user_sessions,      only: [:new, :create, :destroy]
    match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'user_sessions#new',         via: 'get'
    match '/signout', to: 'user_sessions#destroy',     via: 'delete'
  end
  resources :sessions,      only: [:new, :create, :destroy]
  match '/signup',  to: 'owners#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  root to: 'static_pages#home'
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :posts
  has_many :users
  has_many :trade_items
  belongs_to :owner

  def trade_list
    names = trade_items.map { |item| [item.name, item.name] }
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])
    params[:site_id] = @site.id
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params.reject {|k,v|k=="trade_items"})
    respond_to do |format|
      if @site.save
        site_params[:trade_items].split(",").each do |e|
          TradeItem.create(site_id: @site.id, name: e)
        end
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def welcome
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:owner_id, :name, :trade_items)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :owner_id, value: current_owner.id %>
  <%= f.hidden_field :trade_items, value: "" %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Trade Items" %>
  <%= text_field_tag "trade_item1", "", onblur: "return load_items('trade_item1')" %><%= button_to_function "+", "return add_item(2)", id: "button1" %>
  <% (2..9).each do |x| %>
    <%= text_field_tag "trade_item#{x}", "", id: "trade_item#{x}", onblur: "return load_items('trade_item#{x}')", style: "display:none" %><%= button_to_function "+", "return add_item(#{x+1})", id: "button#{x}", style: "display:none" %>
  <% end %>
  <%= text_field_tag "trade_item10", "", id: "trade_item10", onblur: "return load_items('trade_item10')", style: "display:none" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  function add_item(number) {
    document.getElementById("trade_item" + (number).toString()).style.display = "inline";
    document.getElementById("button" + (number).toString()).style.display = "inline";
    document.getElementById("button" + (number-1).toString()).style.display = "none";
  }
  function load_items(name) {
    var item = document.getElementById(name).value;
    if (item != "") {
      var trade_items = document.getElementById("site_trade_items").value;
      if (trade_items == "") { trade_items = item; } else { trade_items = trade_items + "," + item; }
    }
    document.getElementById("site_trade_items").value = trade_items;
  }
</script>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<% provide(:title, @site.name) %>
<div class="row">
  <div class="span8">
    <h4>Name:</h4><%= @site.name %>
    <p><br></p>
    <h4>Trade Items: </h4>
    <% @site.trade_items.each do |item| %>
      <%= item.name %>
    <% end %>
    <p><br></p>
    <%= link_to "Visit Your Site", root_path(subdomain: @site.subdomain) %>
  </div>
</div>

app/views/sites/welcome.html.erb
  <div class="center hero-unit">
    <h1>Welcome to my site</h1>

    <%= link_to "Sign up now!", signup_path(site_id: @site.id),
                                class: "btn btn-large btn-primary" %>
  </div>