config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :owners
  devise_for :users
  resources :owners
  resources :sites do
    get :welcome
    resources :users do
      member do
        get :following, :followers
        post :contact
      end
    end
    resources :posts,    only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :user_sessions,      only: [:new, :create, :destroy]
    match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'user_sessions#new',         via: 'get'
    match '/signout', to: 'user_sessions#destroy',     via: 'delete'
  end
  resources :sessions,      only: [:new, :create, :destroy]
  match '/signup',  to: 'owners#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  root to: 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_owner %></li>
                <li><%= link_to "Settings", edit_owner_path(current_owner) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_site_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_site_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", site_welcome_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Users", site_users_path %></li>
            <li><%= link_to Posts", site_posts_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", site_user_path(id: current_user.id) %></li>
                <li><%= link_to "Settings", edit_site_user_path(id: current_user.id) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", site_signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", site_signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% if site? %>
      <%= render 'layouts/site_header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <% if site? %>
        <%= render 'layouts/site_footer' %>
      <% else %>
        <%= render 'layouts/footer' %>
      <% end %>
    </div>
  </body>
</html>